Document: notekit
Title: Debian notekit Manual
Author: <insert document author here>
Abstract: This manual describes what notekit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/notekit/notekit.sgml.gz

Format: postscript
Files: /usr/share/doc/notekit/notekit.ps.gz

Format: text
Files: /usr/share/doc/notekit/notekit.text.gz

Format: HTML
Index: /usr/share/doc/notekit/html/index.html
Files: /usr/share/doc/notekit/html/*.html
