name: notekit
base: core20 # the base snap is the execution environment for this snap
version: '0.1'
summary: Structured notetaking application
description: |
  This program is a structured notetaking application based on GTK+ 3. 
  Write your notes in instantly-formatted Markdown, organise them in a tree of folders that can be instantly navigated from within the program, and add hand-drawn notes by mouse, touchscreen or digitiser.

grade: devel 
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  notekit:
    # See 'snapcraft plugins'
    source-type: git
    source: https://github.com/blackhole89/notekit
    plugin: nil
    override-build: "
         cmake -G \"Ninja\" . ;
         ninja ;
         mkdir ../install/usr/share/notekit ;
         mkdir ../install/usr/share/notekit/sourceview ;
         mkdir ../install/usr/share/notekit/data ;
         cp cmake-build-Release/output/notekit ../install/usr/share/notekit/notekit ;
         cp -r data ../install/usr/share/notekit/;
         cp -r sourceview ../install/usr/share/notekit/ ;
    "
    build-packages:
        - cmake
        - g++
        - ninja-build
        - libgtkmm-3.0-dev
        - libgtksourceviewmm-3.0-dev
        - libjsoncpp-dev
        - zlib1g-dev
        - libfontconfig1-dev
        - libgdk-pixbuf2.0-dev
    stage-packages:
        - libatk-bridge2.0-0
        - libatk1.0-0
        - libatkmm-1.6-1v5
        - libatspi2.0-0
        - libcairo-gobject2
        - libcairo2
        - libcairomm-1.0-1v5
        - libdatrie1
        - libepoxy0
        - libfontconfig1
        - libfreetype6
        - libgdk-pixbuf2.0-0
        - libglibmm-2.4-1v5
        - libgraphite2-3
        - libgtk-3-0
        - libgtkmm-3.0-1v5
        - libgtksourceview-3.0-1
        - libgtksourceviewmm-3.0-0v5
        - libharfbuzz0b
        - libicu-dev
        - libjsoncpp1
        - libpango-1.0-0
        - libpangocairo-1.0-0
        - libpangoft2-1.0-0
        - libpangomm-1.4-1v5
        - libpixman-1-0
        - libpng16-16
        - libsigc++-2.0-0v5
        - libthai0
        - libwayland-client0
        - libwayland-cursor0
        - libwayland-egl1
        - libx11-6
        - libxau6
        - libxcb-render0
        - libxcb-shm0
        - libxcb1
        - libxcomposite1
        - libxcursor1
        - libxdamage1
        - libxdmcp6
        - libxext6
        - libxfixes3
        - libxi6
        - libxinerama1
        - libxkbcommon0
        - libxml2
        - libxrandr2
        - libxrender1


apps:
  notekit:
    environment: 
        XDG_DATA_DIRS: "/snap/notekit/current/usr/share:$XDG_DATA_DIRS"
        LD_LIBRARY_PATH: "/lib:/usr/lib:/usr/local/lib"
        XDG_CONFIG_HOME: "$SNAP_USER_DATA"
        XDG_DATA_HOME: "$SNAP_USER_DATA"
    #extensions: [gnome-3-28]
    plugs:
        - gsettings
        - home
        - desktop
        - desktop-legacy
        - wayland
        - x11
    command: usr/share/notekit/notekit
