name: notekit
base: core18 # the base snap is the execution environment for this snap
version: '0.1'
summary: Structured notetaking application
description: |
  This program is a structured notetaking application based on GTK+ 3. 
  Write your notes in instantly-formatted Markdown, organise them in a tree of folders that can be instantly navigated from within the program, and add hand-drawn notes by mouse, touchscreen or digitiser.
license: GPL-3.0
grade: devel 
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64

parts:
  notekit:
    # See 'snapcraft plugins'
    source-type: git
    source: https://github.com/noah1510/notekit
    plugin: dump      
    override-build: |
         git checkout snap
         cmake -G "Ninja" . 
         ninja ;
         mkdir -p ../install/usr/share/notekit 
         mkdir -p ../install/usr/share/notekit/sourceview 
         mkdir -p ../install/usr/share/notekit/data 
         cp cmake-build-Release/output/notekit ../install/usr/share/notekit/notekit 
         cp snap_launch_notekit.sh ../install/usr/share/notekit/snap_launch_notekit.sh 
         cp -r data ../install/usr/share/notekit/
         cp -r sourceview ../install/usr/share/notekit/ 
         cp com.github.notekit.desktop ../install/usr/share/notekit/
         sed -i 's|Icon=com.github.notekit.notekit|Icon=${SNAP}/usr/share/notekit/data/icons/notekit_icon.svg|' ${SNAPCRAFT_PART_INSTALL}/usr/share/notekit/com.github.notekit.desktop
    stage:
         # removing dangling symlinks
         - -usr/share/texlive/texmf-dist/ls-R
         - -usr/share/texlive/texmf-dist/tex/generic/config/language.dat.lua
         - -usr/share/texlive/texmf-dist/tex/generic/config/language.def
         - -usr/share/texlive/texmf-dist/tex/generic/config/language.dat
         - -usr/share/texmf/ls-R
    override-stage: |
         snapcraftctl stage
         update-mime-database usr/share/mime
         
         gtk-update-icon-cache
         gdk-pixbuf-query-loaders --update-cache
        
    build-packages:
        - cmake
        - g++
        - ninja-build
        - libgtkmm-3.0-dev
        - libgtksourceviewmm-3.0-dev
        - libjsoncpp-dev
        - zlib1g-dev
        - libfontconfig1-dev
        - libgdk-pixbuf2.0-dev
        - git

        - appstream-util
        - libgtk-3-dev
        - libpoppler-glib-dev
        - libxml2-dev
        - libsndfile-dev
        - liblua5.3-dev
        - libzip-dev
        - dvipng
    stage-packages:
        - libatk-bridge2.0-0
        - libatk1.0-0
        - libatkmm-1.6-1v5
        - libatspi2.0-0
        - libcairo-gobject2
        - libcairo2
        - libcairomm-1.0-1v5
        - libdatrie1
        - libepoxy0
        - libfontconfig1
        - libfreetype6
        - libgdk-pixbuf2.0-dev
        - libglibmm-2.4-1v5
        - libgraphite2-3
        - libgtk-3-0
        - libgtkmm-3.0-1v5
        - libgtksourceview-3.0-1
        - libgtksourceviewmm-3.0-0v5
        - libharfbuzz0b
        - libicu-dev
        - libjsoncpp1
        - libpango-1.0-0
        - libpangocairo-1.0-0
        - libpangoft2-1.0-0
        - libpangomm-1.4-1v5
        - libpixman-1-0
        - libpng16-16
        - libsigc++-2.0-0v5
        - libthai0
        - libwayland-client0
        - libwayland-cursor0
        - libwayland-egl1
        - libx11-6
        - libxau6
        - libxcb-render0
        - libxcb-shm0
        - libxcb1
        - libxcomposite1
        - libxcursor1
        - libxdamage1
        - libxdmcp6
        - libxext6
        - libxfixes3
        - libxi6
        - libxinerama1
        - libxkbcommon0
        - libxml2
        - libxrandr2
        - libxrender1

        - adwaita-icon-theme
        - faenza-icon-theme
        - gnome-icon-theme
        - libpng++-dev

        - libzip-dev
        - libtiff5

        - libjpeg-turbo8
        - liblcms2-2
        - libnspr4
        - libnss3
        - libpoppler73
        - libpoppler-glib8
        - binutils

        - shared-mime-info
        
        - texlive-latex-base
        - texlive-binaries
        - texlive-latex-extra

apps:
  notekit:
    extensions: [gnome-3-28]
    desktop: usr/share/notekit/com.github.notekit.desktop
    plugs:
        - gsettings
        - home
        - desktop
        - desktop-legacy
        - wayland
        - x11
    command: usr/share/notekit/snap_launch_notekit.sh
